Marketplace/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^', include('listings.urls', namespace="listings")),

    # Static pages
    url(r'^search/$', views.search, name="search"),
    url(r'^map/', TemplateView.as_view(template_name="Marketplace/map.html"), name="map"),

    # Ajax search
    url(r'^search_data/$', views.search, name="search_data"),

    # Public pages
    url(r'^user/(?P<user>[0-9A-Za-z]+)/$', views.public_profile, name="public_profile"),

    # Profile tools
    url(r'^accounts/', include('allauth.urls'), name='accounts'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^accounts/add-listing/$', views.add_listing, name='add_listing'),
    url(r'^accounts/publish/(?P<listing_id>[0-9]+)/$', views.publish_listing, name='publish_listing'),
    url(r'^accounts/unpublish/(?P<listing_id>[0-9]+)/$', views.unpublish_listing, name='unpublish_listing'),
    url(r'^accounts/delete/(?P<listing_id>[0-9]+)/$', views.delete_listing, name='delete_listing'),

    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/$', views.edit_listing, name='edit_listing'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/description$', views.edit_listing_description, name='edit_listing_description'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/details$', views.edit_listing_details, name='edit_listing_details'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/location$', views.edit_listing_location, name='edit_listing_location'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/photos$', views.edit_listing_photos, name='edit_listing_photos'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/calendar$', views.edit_listing_calendar, name='edit_listing_calendar'),

    # Ajax photo upload views
    url(r'^upload/(?P<listing_id>[0-9]+)', views.upload, name='jfu_upload'),
    url(r'^delete/(?P<pk>\d+)$', views.upload_delete, name='jfu_delete'),
]

sublet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^', include('listings.urls', namespace="listings")),

    # Main pages
    url(r'^$', TemplateView.as_view(template_name="sublet/landing.html"), name="landing"),
    url(r'^search/$', views.search, name="search"),
    url(r'^user/(?P<user>[0-9A-Za-z]+)/$', views.public_profile, name="public_profile"),
    url(r'^listing/(?P<listing>[0-9A-Za-z]+)/$', views.listing, name="listing"), # Move this to listings


    # ajax
    url(r'^star/$', views.ajax_star, name="star"),
    url(r'^bug-report/$', views.ajax_bug_report, name="bug-report"),
    url(r'^contact/$', views.ajax_contact, name="contact"),


    # Profile tools
    url(r'^accounts/', include('allauth.urls'), name='accounts'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User
from allauth.account.models import EmailAddress
from allauth.socialaccount.models import SocialAccount
from listings.models import Listing


UNI_DIV = (('NA', 'Not Affiliated'),
    ('first', 'First Year'),
    ('second', 'Second Year'),
    ('third', 'Third Year'),
    ('fourth', 'Fourth Year'),
    ('grad', 'Graduate Student'),
    ('faculty', 'Faculty Member'),
    ('other', 'Other division'))


class ExtendedUser(models.Model):
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE, default="0", null=True)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures',
        default="/static/img/accounts/empty-photo.png", blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    uni_division = models.CharField(choices=UNI_DIV, max_length=50, blank=True)
    home_town = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    starred = models.ManyToManyField(Listing)

    # Check if the user has a verified uchicago email address
    def uchicago_email(self):
        email_list = EmailAddress.objects.filter(user=self.user, verified=True)
        for email in email_list:
            if '@uchicago.edu' in email.email:
                return True
        return False

    def social_account(self, account):
        if SocialAccount.objects.filter(user=self.user, provider=account):
            return True
        return False

    def get_listings(self):
        return Listing.objects.filter(user=self.user)

    def get_absolute_url(self):
        return reverse('public_profile', args=[str(self.id)])

    """ Checks whether the provided listing id is starred by user """
    def is_starred(self, listing_id):
        if (self.starred.filter(id=listing_id).exists()):
            return True
        return False

    def get_primary_email(self):
        return EmailAddress.objects.get(user=self.user, primary=True)

    def get_verifications(self):
        """Gets all verified/connected verifications and unconnected verifications"""
        v = [("Email Address", "Verified")]
        uv = []
        if (self.uchicago_email()):
            v.append(("UChicago Email", "Verified"))
        else:
            uv.append(("UChicago Email", "Not Verified"))

        if (self.social_account('facebook')):
            v.append(("Facebook", "Connected"))
        else:
            uv.append(("Facebook", "Not Connected"))

        if (self.social_account('google')):
            v.append(("Google", "Connected"))
        else:
            uv.append(("Google", "Not Connected"))

        if (self.social_account('linkedin')):
            v.append(("Linkedin", "Connected"))
        else:
            uv.append(("Linkedin", "Not Connected"))
        return (v, uv)


def user_post_save(sender, instance, created, **kwargs):
    # Create a user profile when a new user account is created
    if created:
        p = ExtendedUser()
        p.user = instance
        p.save()


post_save.connect(user_post_save, sender=User)

listings/forms.py
from django import forms
from .models import Listing


class EditDescriptionForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ('name', 'summary', 'price')


class EditLocationForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ('street_address', 'apt', 'city', 'state', 'zip_code', 'latitude', 'longitude')


class EditDetailsForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ('bed_size', 'roommate_count', 'bathroom', 'ac', 'in_unit_washer_dryer', 'tv',
            'cable_tv', 'internet', 'wheel_chair_accessible', 'pets_live_here')
        widgets = {
            'bed_size': forms.Select(attrs={'class': 'ui dropdown'}),
            'bathroom': forms.Select(attrs={'class': 'ui dropdown'}),
            'roommate_count': forms.Select(attrs={'class': 'ui dropdown'}),
        }


class EditCalendarForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ('fall_quarter', 'winter_quarter', 'spring_quarter', 'summer_quarter', 'start_date', 'end_date')

sublet/forms.py
from django import forms
from captcha.fields import ReCaptchaField


class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, required=False)
    email = forms.EmailField(label='Email Address', max_length=200, required=True)
    subject = forms.CharField(label='Message Purpose', required=True)
    message = forms.CharField(label='Message', widget=forms.Textarea, max_length=2000, required=True)
    cc_myself = forms.BooleanField(required=False)


class ListingForm(forms.Form):
    email = forms.EmailField(label='Email Address', max_length=200, required=True)
    message = forms.CharField(label='Message', max_length=400, required=True, widget=forms.Textarea)
    captcha = ReCaptchaField(label='Captcha')


class ListingFormAuthenticated(forms.Form):
    message = forms.CharField(label='Message', max_length=400, required=True, widget=forms.Textarea)
    # captcha = ReCaptchaField(label='Captcha')

listings/views.py
import os

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.http import require_POST
from django.views.generic.edit import FormView
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from .utility import listing_ownership
from .models import Listing, Photo, MAX_PHOTOS, ACCEPTED_IMAGE_TYPES
from .forms import EditDescriptionForm, EditDetailsForm, EditLocationForm, EditCalendarForm
from jfu.http import upload_receive, UploadResponse, JFUResponse

@login_required
def add_listing(request):
    new_listing = Listing(user=request.user)
    new_listing.save()
    return HttpResponseRedirect(reverse('listings:edit_listing_description', args=(new_listing.id,)))


@login_required
def edit_listing(request, listing_id):
    return HttpResponseRedirect(reverse('listings:edit_listing_description', args=(listing_id,)))


# Change these form views to one class
@login_required
@listing_ownership
def edit_listing_description(request, listing):
    if request.method == "POST":
        form = EditDescriptionForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('listings:edit_listing_location', args=(listing.id,)))
    else:
        form = EditDescriptionForm(instance=listing)
    context = {'form': form, 'user': request.user, 'listing': listing}
    return render(request, 'listing/edit_listing_description.html', context)


@login_required
@listing_ownership
def edit_listing_location(request, listing):
    if request.method == "POST":
        form = EditLocationForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('listings:edit_listing_details', args=(listing.id,)))
    else:
        form = EditLocationForm(instance=listing)
    context = {'form': form, 'user': request.user, 'listing': listing}
    return render(request, 'listing/edit_listing_location.html', context)


@login_required
@listing_ownership
def edit_listing_details(request, listing):
    if request.method == "POST":
        form = EditDetailsForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('listings:edit_listing_photos', args=(listing.id,)))
    else:
        form = EditDetailsForm(instance=listing)
    context = {'form': form, 'user': request.user, 'listing': listing}
    return render(request, 'listing/edit_listing_details.html', context)


@login_required
@listing_ownership
def edit_listing_calendar(request, listing):
    if request.method == "POST":
        form = EditCalendarForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('listings:edit_listing_calendar', args=(listing.id,)))
    else:
        form = EditCalendarForm(instance=listing)
    context = {'form': form, 'user': request.user, 'listing': listing}
    return render(request, 'listing/edit_listing_calendar.html', context)


@login_required
@listing_ownership
def edit_listing_photos(request, listing):
    photos = Photo.objects.filter(listing=listing.id)
    context = {'accepted_mime_types': 'image/*', 'listing': listing, 'photos': photos}
    return render(request, 'listing/edit_listing_photos.html', context)


@login_required
@require_POST
@listing_ownership
def upload(request, listing):
    if Photo.objects.filter(listing=listing).count() >= MAX_PHOTOS:
        return UploadResponse(request, {'error': 'Max number of photos reached.'})

    image = upload_receive(request)
    description = request.POST.get("description[]") or image.name

    if not image.name.endswith(ACCEPTED_IMAGE_TYPES):
        return UploadResponse(request, {'error': 'Filetype not supported.'})

    instance = Photo(image=image, listing=listing, description=description)
    instance.save()

    file_dict = {
        'name': image.name,
        'description': description,
        'url': instance.image.url,
        'thumbnailUrl': instance.image_s.url,
        'deleteUrl': reverse('listings:jfu_delete', kwargs={'pk': instance.pk}),
        'deleteType': 'POST',
    }
    return UploadResponse(request, file_dict)


@login_required
@require_POST
def upload_delete(request, pk):
    try:
        photo = Photo.objects.get(pk=pk)
        if photo.listing.user != request.user:
            success = False
            return JFUResponse(request, success)
        photo.delete()
        success = True
    except Photo.DoesNotExist:
        success = False
    return JFUResponse(request, success)


@login_required
@listing_ownership
def publish_listing(request, listing):
    if (listing.listing_complete()):
        listing.published = True
        listing.save()
        return HttpResponseRedirect(reverse("accounts:listings"))
    else:
        # In case someone is sneaky and tries to publish before complete
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
@listing_ownership
def unpublish_listing(request, listing):
    listing.published = False
    listing.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
@listing_ownership
def delete_listing(request, listing):
    listing.delete()
    return HttpResponseRedirect(reverse("accounts:listings"))

templates/sublet/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}Contact{% endblock %}

{% block content %}
<div id="account" class="ui centered one column grid stackable container" style="margin-top: 20px;">
    <div class="eight wide column">
        <form class="ui form" method="POST" action="">
            <div class="ui secondary top attached segment">
                <h4>Contact</h4>
            </div>
            <div class="ui attached padded segment">
                {% csrf_token %}
                <div class="ui two column grid">
                    <div class="row">
                        <div class="four wide right aligned column">
                            <label class="inline-label">Your Name</label>
                        </div>
                        <div class="twelve wide column">
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="four wide right aligned column">
                            <label class="inline-label">Email Address</label>
                        </div>
                        <div class="twelve wide column">
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="four wide right aligned column">
                            <label class="inline-label">Subject</label>
                        </div>
                        <div class="twelve wide column">
                            {{ form.subject }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="four wide right aligned column">
                            <label class="inline-label">Message</label>
                        </div>
                        <div class="twelve wide column">
                            {{ form.message }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui bottom attached segment">
                <div class="ui one column right aligned grid">
                    <div class="ui sixteen wide column">
                        <button class="ui customblue button" type="submit" style="width:90px;">Send</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/sublet/landing.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}Home{% endblock %}

{% block content %}
<div id="landing">

  <div class="ui inverted vertical masthead center aligned segment">

      <div class="ui text container">
        <h1 class="ui inverted header">
          Looking to Sublet?
        </h1>
        <h2>List or find a sublet etc etc.</h2>
        <a class="ui huge customblue primary button" href="{% url 'search' %}">Find a sublet  <i class="right search icon"></i></a>
        <a class="ui huge customblue primary button" href="{% url 'account_signup' %}">List a sublet <i class="right home icon"></i></a>
      </div>

  </div>
</div>
{% endblock %}

templates/sublet/listing.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load upto %}

{% block head_title %}{{listing.name}}{% endblock %}

{% block head %}
<script src='https://www.google.com/recaptcha/api.js'></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/unslider/2.0.3/css/unslider.css">
<link rel="stylesheet" type="text/css" href="{% static "css/listing.css" %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">

{% endblock head %}

{% block content %}
<div class="ui centered one column grid stackable container">
    <div class="row">
        <div class="ui thirteen wide column">
            <div class="slider image">
                <ul>
                    <li>
                        <div class="slider-photo">
                            {% with cover_photo=listing.get_cover_photo %}
                            <img src="{{cover_photo.image.url}}">
                            <a class="slider-link middle lightbox" href="{{cover_photo.image.url}}"
                                title="{{cover_photo.description}}"></a>
                            {% endwith %}
                        </div>

                    </li>
                    {% for photo in listing.get_remaining_photos %}
                    <li>
                        <div class="loader-container">
                            <div class="ui disabled active dimmer">
                                <div class="ui active text loader">Loading Image</div>
                            </div>
                        <div>
                        <div class="slider-photo">
                            <img data-src="{{photo.image.url}}">
                             <a class="slider-link middle lightbox" href="{{photo.image.url}}"
                                title="{{photo.description}}"></a>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div class="ui content row">
        <div class="ui eight wide column">
            <div class="icon-row">
                <i class="ui large share alternate icon"></i>
                <a style="color: #565a5c" href="{{ listing.user.extendeduser.get_absolute_url }}"><i class="ui large user icon"></i></a>
                <i style="padding-top: 2px;" class="ui large {{starred}} star icon" onclick="star(this, {{listing.id}})" data-content="Star this listing"></i>
            </div>
            <span class="listing-header">{{listing.name}}</span>
            <p>Rent: &#36;<strong>{{listing.price}} per month</strong></p>



            <div class="ui divider"></div>
            <h4>Description</h4>
            <p>{{listing.summary|linebreaks}}</p>

            <div class="ui divider"></div>
            <h4>Amenities</h4>
            <div class="ui two column grid">
                <div class="ui eight wide column">
                    <!-- Icons made by Freepik http://www.freepik.com" from http://www.flaticon.com is licensed by CC 3.0 -->
                    <div id="ac" class="amenities {% if not listing.ac %}nope{% endif %}">
                        <img src="{% static "img/amenities/ac.svg" %}">
                        <div class="text">Air conditioning</div>
                    </div>
                    <div id="washer" class="amenities {% if not listing.in_unit_washer_dryer %}nope{% endif %}">
                        <img src="{% static "img/amenities/washer.svg" %}">
                        <div class="text">In unit washer/dryer</div>
                    </div>
                    <div id="tv" class="amenities {% if not listing.tv %}nope{% endif %}">
                        <img src="{% static "img/amenities/tv.svg" %}">
                        <div class="text">Television</div>
                    </div>
                    <div id="cable" class="amenities {% if not listing.cable_tv %}nope{% endif %}">
                        <img src="{% static "img/amenities/cable.svg" %}">
                        <div class="text">Cable TV</div>
                    </div>
                </div>
                <div class="ui eight wide column">
                    <div id="internet" class="amenities {% if not listing.internet %}nope{% endif %}">
                        <img src="{% static "img/amenities/internet.svg" %}">
                        <div class="text">Internet/WiFi</div>
                    </div>
                    <div id="wheelchair" class="amenities {% if not listing.wheel_chair_accessible %}nope{% endif %}">
                        <img src="{% static "img/amenities/wheelchair.svg" %}">
                        <div class="text">Wheelchair accessible</div>
                    </div>
                    <div id="pets" class="amenities {% if not listing.pets_live_here %}nope{% endif %}">
                        <img src="{% static "img/amenities/pets.svg" %}">
                        <div class="text">Pets live here</div>
                    </div>
                </div>
            </div>

            <div class="ui divider"></div>
            <h4>Location</h4>
            <div id="map" style="width:100%; height:350px;"></div>
            <div id="latitude" style="display: none">{{listing.latitude}}</div>
            <div id="longitude" style="display: none">{{listing.longitude}}</div>

            <div class="ui divider"></div>
            <h4>Owner</h4>
            <div class="ui two column grid">
                <div class="four wide column">
                    <img class="ui image" src="{{listing.user.extendeduser.profile_picture.url}}">
                </div>
                <div class="twelve wide column">
                    <h5>{{listing.user.extendeduser.first_name}} {{listing.user.extendeduser.last_name}}</h5>
                    <p>Division: <strong>{{listing.user.extendeduser.get_uni_division_display}}</strong><br>
                    Hometown: <strong>{{listing.user.extendeduser.home_town}}</strong><br>
                    <a href="{{listing.user.extendeduser.get_absolute_url}}">View profile</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="ui five wide column">
            <form class="ui form" method="POST" action="">
                <div class="ui secondary top attached segment">
                    <h4>Contact Renter</h4>
                </div>
                <div style="padding-top: 12px;" class="ui bottom attached padded segment">
                    {% csrf_token %}
                    {% if user.is_anonymous %}
                        <div class="ui field">
                            <label>Email</label>
                            {{form.email}}
                        </div>
                    {% endif %}
                     {% if user.is_authenticated %}
                    {% endif %}
                    <div class="ui field">
                        <label>Message</label>
                        {{form.message|attr:"rows:5"}}
                    </div>
                    <div class="ui field">
                        {{form.captcha}}
                    </div>
                    {% if form.errors %}
                    <div class="ui negative message">
                        <ul class="list">
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ field.label }}: {{ error|escape }}</li>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <li>{{ error|escape }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    <div class="ui divider"></div>
                    <button class="ui fluid customblue button" type="submit">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="//cdn.jsdelivr.net/velocity/1.2.3/velocity.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/unslider/2.0.3/js/unslider-min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<script type="text/javascript">
    var CSRF_TOKEN = "{{ csrf_token }}";
</script>
<script type="text/javascript" src="{% static "js/listing-page.js" %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAP5xmOaC6toBn_BrLSA_DZeLBMPl1lm3w&libraries=places&callback=initMap" async defer></script>
{% endblock scripts %}

templates/sublet/public_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}   TEMPORARY   {% endblock %}
{% block content %}

<div id="account" class="ui centered two column grid stackable container" style="margin-top: 20px;">
    <div class="four wide column">
        <div class="ui fluid card">
            <div class="image">
                <img src="{% static "/static/img/accounts/empty-photo.png" %}">
            </div>
            <div class="content">
                <p class="header">{{ user.extendeduser.first_name }} {{ user.extendeduser.last_name }}</p>
                <!-- <div class="description ">
                    <strong>Location:</strong>
                </div> -->
            </div>
        </div>
        <div class="ui secondary top attached segment" style="margin-top: 30px;">
          <h4 class="">Verifications</h4>
        </div>
        <div class="ui bottom attached padded segment">
            <div class="ui list">
                {% for header, text in verified %}
                    <div class="item">
                        <i class="ui green checkmark icon"></i>
                        <div class="content">
                            <div class="header">{{ header }}</div>
                            {{ text }}
                        </div>
                    </div>
                {% endfor %}
                {% for header, text in unverified %}
                    <div class="item greyed">
                        <i class="ui grey minus icon"></i>
                        <div class="content">
                            <div class="header">{{ header }}</div>
                            {{ text }}
                        </div>
                    </div>
                {% endfor %}
            </div>


        </div>
    </div>
    <div class="ten wide column">
        <div class="ui secondary top attached segment">
          <h4 class="">About me</h4>
        </div>
        <div class="ui bottom attached padded segment">
            {{ user.extendeduser.description }}
        </div>

        <div class="ui secondary top attached segment">
          <h4 class="">Listings</h4>
        </div>
        <div class="ui bottom attached padded segment">
            <div class="ui small images">
                {% for listing in user.extendeduser.get_listings %}
                    <img src="{{ listing.get_cover_photo.image.url }}">
                    {{ listing.name }}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}