Marketplace/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^', include('listings.urls', namespace="listings")),

    # Static pages
    url(r'^search/$', views.search, name="search"),
    url(r'^map/', TemplateView.as_view(template_name="Marketplace/map.html"), name="map"),

    # Ajax search
    url(r'^search_data/$', views.search, name="search_data"),

    # Public pages
    url(r'^user/(?P<user>[0-9A-Za-z]+)/$', views.public_profile, name="public_profile"),

    # Profile tools
    url(r'^accounts/', include('allauth.urls'), name='accounts'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = [

    # ajax stuff
    url(r'^accounts/edit_profile/use_fb_photo/$', views.ajax_fb_photo, name='ajax_fb_photo'),

    # Account pages
    url(r'^accounts/dashboard/$', views.dashboard, name='home'),
    url(r'^accounts/listings/$', views.your_listings, name='listings'),
    url(r'^accounts/starred_listings/$', views.starred_listings, name='starred_listings'),
    url(r'^accounts/edit_profile/$', views.edit_profile, name='edit_profile'),

    # Account verifications
    url(r'^accounts/verification/$',
        views.verification, name='verification'),
    url(r'^accounts/disconnect/(?P<service>[0-9A-Za-z]+)',
        views.disconnect_service, name='disconnect_service'),

    # Account settings
    url(r'^accounts/settings/$',
        login_required(views.settings.as_view()), name='settings'),
    url(r'^accounts/password_change_successful/$',
        TemplateView.as_view(template_name='account/password_change_successful.html'),
        name='password_change_successful'),
    url(r'^accounts/email_add_successful/$',
        login_required(views.email_add_successful.as_view()), name='email_add_successful'),
]

listings/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^accounts/add-listing/$', views.add_listing, name='add_listing'),
    url(r'^accounts/publish/(?P<listing_id>[0-9]+)/$', views.publish_listing, name='publish_listing'),
    url(r'^accounts/unpublish/(?P<listing_id>[0-9]+)/$', views.unpublish_listing, name='unpublish_listing'),
    url(r'^accounts/delete/(?P<listing_id>[0-9]+)/$', views.delete_listing, name='delete_listing'),

    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/$', views.edit_listing, name='edit_listing'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/description$', views.edit_listing_description, name='edit_listing_description'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/details$', views.edit_listing_details, name='edit_listing_details'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/location$', views.edit_listing_location, name='edit_listing_location'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/photos$', views.edit_listing_photos, name='edit_listing_photos'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/calendar$', views.edit_listing_calendar, name='edit_listing_calendar'),

    # Ajax photo upload views
    url(r'^upload/(?P<listing_id>[0-9]+)', views.upload, name='jfu_upload'),
    url(r'^delete/(?P<pk>\d+)$', views.upload_delete, name='jfu_delete'),
]

sublet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^', include('listings.urls', namespace="listings")),

    # Main pages
    url(r'^$', TemplateView.as_view(template_name="sublet/landing.html"), name="landing"),
    url(r'^search/$', views.search, name="search"),
    url(r'^user/(?P<user>[0-9A-Za-z]+)/$', views.public_profile, name="public_profile"),
    url(r'^listing/(?P<listing>[0-9A-Za-z]+)/$', views.listing, name="listing"), # Move this to listings


    # ajax
    url(r'^star/$', views.ajax_star, name="star"),
    url(r'^bug-report/$', views.ajax_bug_report, name="bug-report"),
    url(r'^contact/$', views.ajax_contact, name="contact"),


    # Profile tools
    url(r'^accounts/', include('allauth.urls'), name='accounts'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>{% block head_title %}{% endblock %} | Sublet</title>

	{% load staticfiles %}

 	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.4/semantic.min.css">
  <!--<link rel="stylesheet" href="{% static "css/semantic.min.css" %}">-->
	<link rel="stylesheet" href="{% static "css/main.css" %}">

  {% block head %}
  {% endblock %}

  <body>
    <div class="ui sidebar inverted vertical menu">
      <a href="{% url "search" %}" class="{% if request.resolver_match.url_name == 'search' %}active{% endif %} item"><i class="search icon"></i>Search Listings</a>

      {% if user.is_anonymous %}
        <a href="{% url 'account_signup' %}" class="item {% if request.resolver_match.url_name == 'account_signup' %}active{% endif %}">Sign Up</a>
        <a href="{% url 'account_login' %}" class="item {% if request.resolver_match.url_name == 'account_login' %}active{% endif %}">Log In</a>
        {% endif %}

      {% if user.is_authenticated %}
        <a href="{% url "listings:add_listing" %}" class="ui item"><i class="plus icon"></i>Post Listing</a>
        <a href="{% url 'accounts:home' %}" class="{% if request.resolver_match.url_name == "home" %}active{% endif %} item">
          <i class="dashboard icon"></i>
          Dashboard
        </a>
        <a href="{% url 'accounts:listings' %}" class="{% if request.resolver_match.url_name == "listings" %}active{% endif %} item">
          <i class="home icon"></i>
          Your listings
        </a>
        <a href="{% url 'accounts:starred_listings' %}" class="{% if request.resolver_match.url_name == "starred_listings" %}active{% endif %} item">
          <i class="star icon"></i>
          Starred listings
        </a>
        <a href="{% url 'accounts:verification' %}" class="{% if request.resolver_match.url_name == "verification" %}active{% endif %} item">
          <i class="checkmark icon"></i>
          Verifications
        </a>
        <a href="{% url 'accounts:edit_profile' %}" class="{% if request.resolver_match.url_name == "edit_profile" %}active{% endif %} item">
          <i class="user icon"></i>
          Edit Profile
        </a>
        <a href="{% url 'accounts:settings' %}" class="{% if request.resolver_match.url_name == "settings" %}active{% endif %} item">
          <i class="setting icon"></i>
          Settings
        </a>
        <a href="{% url 'account_logout' %}" class="item">
          <i class="rocket icon"></i>
          Logout
        </a>
      {% endif %}
    </div>

    <div class="pusher">
      <div id="top-menu" class="ui large {% if request.resolver_match.url_name == "landing" %}fixed inverted transparent{% endif %} menu">
        <a class="header item logo" href="{% url 'landing' %}">
          <!-- <img class="logo" src="{% static "img/logo_200x200.png" %}"> -->
          Sublet @ UChicago
        </a>
        <div class="computer-menu right menu">
          <a href="{% url "search" %}" class="ui item">
            <i class="search icon"></i>
            Search Listings
          </a>
          {% if user.is_anonymous %}
          <a href="{% url 'account_signup' %}" class="item">
            Sign Up
          </a>
          <a href="{% url 'account_login' %}" class="item">
            Log In
          </a>
          {% endif %}
          {% if user.is_authenticated %}
          <a href="{% url "listings:add_listing" %}" class="ui item">
            <i class="plus icon"></i>
            Post Listing
          </a>
          <div id="user" class="ui right dropdown browse item">
            <i class="ui home icon"></i>Home
            <div class="menu">
              <a href="{% url 'accounts:home' %}" class="item"><i class="dashboard icon"></i> Dashboard</a>
              <a href="{% url "accounts:listings" %}" class="item"><i class="home icon"></i> Your Listings</a>
              <a href="{% url "accounts:starred_listings" %}" class="item"><i class="star icon"></i> Starred Listings</a>
              <a href="{% url "accounts:edit_profile" %}" class="item"><i class="user icon"></i> Edit Profile</a>
              <a href="{% url "accounts:settings" %}" class="item"><i class="setting icon"></i> Settings</a>
              <a class="item" href="{% url 'account_logout' %}"><i class="rocket icon"></i> Logout</a>
            </div>
          </div>
          {% endif %}
        </div>
        <div class="mobile-menu right menu">
          <a class="menu-button item"><i class="sidebar large icon"></i></a>
        </div>
      </div>

      <div id="content">
        {% block content %}
        {% endblock %}
      </div>

      <div class="ui inverted vertical footer segment">
        <div class="ui center aligned container grid">
          <div class="ui twelve wide column">
            <div class="ui stackable inverted divided grid">
              <div class="four wide column">
                <h4 class="ui inverted header">Development</h4>
                <div class="ui inverted link list">
                  <a href="{% url "contact" %}" id="contact" class="item">Contact</a>
                  <a href="" id="bug" class="item">Report a bug</a>
                  <a href="https://github.com/NilsJPWerner/Sublet-Uchicago" class="item">Source Code</a>
                  <a href="#" class="item">Blog</a>
                </div>
              </div>
              <div class="four wide column">
                <h4 class="ui inverted header">Site Map</h4>
                <div class="ui inverted link list">
                  <a href="{% url "search" %}" class="item">Search</a>
                  <a href="{% url "accounts:home" %}" class="item">Dashboard</a>
                  <a href="{% url "accounts:listings" %}" class="item">Your Listings</a>
                  <a href="{% url "accounts:edit_profile" %}" class="item">Edit Profile</a>
                </div>
              </div>
              <div class="eight wide column">
                <h4 class="ui inverted header">Contribute on Github</h4>
                <div class="ui inverted link list" style="margin-top: 1.3em;">
                  <a href="https://github.com/NilsJPWerner/Sublet-Uchicago" class="ui basic inverted button"><i class="ui large star icon"></i>Star</a>
                  <a href="https://github.com/NilsJPWerner/Sublet-Uchicago/fork" class="ui basic inverted button"><i class="ui large fork icon"></i>Fork</a>
                  <a href="https://github.com/NilsJPWerner/Sublet-Uchicago" class="ui basic inverted button"><i class="ui large eye icon"></i>Watch</a>
                  <a href="mailto:nils.jp.werner@gmail.com" class="item" style="margin-top: 1em;">nils.jp.werner@gmail.com</a>
                </div>
              </div>
            </div>
            <div class="ui inverted section divider"></div>
            <div class="ui center aligned horizontal inverted small divided link list">
              <a class="item" href="#">Terms and Conditions</a>
              <a class="item" href="#">Privacy Policy</a>
              <a class="item" href="http://nils.tech">© 2016 Nils Werner</a>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div id="bug-modal" class="ui small modal">
      <div class="header">
        Submit a bug report
      </div>
      <div class="content">
        <form id="bug-form" class="ui form" action="/bug-report/">
          {% csrf_token %}
          <div class="field">
            <label>Email Address</label>
            <input name="bug-email" type="email">
          </div>
          <div class="field">
            <label>Include a description of what the bug is and how you got to it</label>
            <textarea name="bug-report"></textarea>
          </div>
          <div class="field">
            <div class="ui checkbox">
              <input type="checkbox" checked="checked" name="bug-contactme" tabindex="0" class="hidden">
              <label>It's okay to contact me.</label>
            </div>
          </div>
          <div class="ui error message"></div>
        </form>
      </div>
      <div class="actions">
        <div class="ui cancel button">Cancel</div>
        <button id="bug-report-send" class="ui green button" type="submit" form="bug-form">Send</button>
      </div>
    </div>


    <div id="contact-modal" class="ui small modal">
      <div class="header">
        Contact me
      </div>
      <div class="content">
        <form id="contact-form" class="ui form" action="/contact/">
          {% csrf_token %}
          <div class="field">
            <label>Your Name</label>
            <input name="contact-name" type="text">
          </div>
          <div class="field">
            <label>Email Address</label>
            <input name="contact-email" type="email">
          </div>
          <div class="field">
            <label>Subject</label>
            <input name="contact-subject" type="text">
          </div>
          <div class="field">
            <label>Message</label>
            <textarea name="contact-message"></textarea>
          </div>
          <div class="ui error message"></div>
        </form>
      </div>
      <div class="actions">
        <div class="ui cancel button">Cancel</div>
        <button id="contact-send" class="ui green button" type="submit" form="contact-form">Send</button>
      </div>
    </div>


    {% block jquery %}
      {% comment %}
        DONT REMOVE THIS
        This block is used to get rid of the this line for the jfu uploader to prevent jquery conflicts
        Yes I know this is a hack but omg the jfu plugin is atrocious and this was the easiest solution
      {% endcomment %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
      <!-- <script src="{% static "js/jquery-2.1.4.min.js" %}" type="text/javascript"></script>-->
    {% endblock %}

   <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.4/semantic.min.js"></script>
    <!-- <script src="{% static "js/semantic.min.js" %}" type="text/javascript"></script>-->
    <script src="{% static "js/main.js" %}" type="text/javascript"></script>

    {% block scripts %}
    {% endblock %}

  </body>
</html>