Marketplace/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^', include('listings.urls', namespace="listings")),

    # Static pages
    url(r'^search/$', views.search, name="search"),
    url(r'^map/', TemplateView.as_view(template_name="Marketplace/map.html"), name="map"),

    # Ajax search
    url(r'^search_data/$', views.search, name="search_data"),

    # Public pages
    url(r'^user/(?P<user>[0-9A-Za-z]+)/$', views.public_profile, name="public_profile"),

    # Profile tools
    url(r'^accounts/', include('allauth.urls'), name='accounts'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = [

    # ajax stuff
    url(r'^accounts/edit_profile/use_fb_photo/$', views.ajax_fb_photo, name='ajax_fb_photo'),

    # Account pages
    url(r'^accounts/dashboard/$', views.dashboard, name='home'),
    url(r'^accounts/listings/$', views.your_listings, name='listings'),
    url(r'^accounts/starred_listings/$', views.starred_listings, name='starred_listings'),
    url(r'^accounts/edit_profile/$', views.edit_profile, name='edit_profile'),

    # Account verifications
    url(r'^accounts/verification/$',
        views.verification, name='verification'),
    url(r'^accounts/disconnect/(?P<service>[0-9A-Za-z]+)',
        views.disconnect_service, name='disconnect_service'),

    # Account settings
    url(r'^accounts/settings/$',
        login_required(views.settings.as_view()), name='settings'),
    url(r'^accounts/password_change_successful/$',
        TemplateView.as_view(template_name='account/password_change_successful.html'),
        name='password_change_successful'),
    url(r'^accounts/email_add_successful/$',
        login_required(views.email_add_successful.as_view()), name='email_add_successful'),
]

listings/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^accounts/add-listing/$', views.add_listing, name='add_listing'),
    url(r'^accounts/publish/(?P<listing_id>[0-9]+)/$', views.publish_listing, name='publish_listing'),
    url(r'^accounts/unpublish/(?P<listing_id>[0-9]+)/$', views.unpublish_listing, name='unpublish_listing'),
    url(r'^accounts/delete/(?P<listing_id>[0-9]+)/$', views.delete_listing, name='delete_listing'),

    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/$', views.edit_listing, name='edit_listing'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/description$', views.edit_listing_description, name='edit_listing_description'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/details$', views.edit_listing_details, name='edit_listing_details'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/location$', views.edit_listing_location, name='edit_listing_location'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/photos$', views.edit_listing_photos, name='edit_listing_photos'),
    url(r'^accounts/edit-listing/(?P<listing_id>[0-9]+)/calendar$', views.edit_listing_calendar, name='edit_listing_calendar'),

    # Ajax photo upload views
    url(r'^upload/(?P<listing_id>[0-9]+)', views.upload, name='jfu_upload'),
    url(r'^delete/(?P<pk>\d+)$', views.upload_delete, name='jfu_delete'),
]

sublet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^', include('listings.urls', namespace="listings")),

    # Main pages
    url(r'^$', TemplateView.as_view(template_name="sublet/landing.html"), name="landing"),
    url(r'^search/$', views.search, name="search"),
    url(r'^user/(?P<user>[0-9A-Za-z]+)/$', views.public_profile, name="public_profile"),
    url(r'^listing/(?P<listing>[0-9A-Za-z]+)/$', views.listing, name="listing"), # Move this to listings


    # ajax
    url(r'^star/$', views.ajax_star, name="star"),
    url(r'^bug-report/$', views.ajax_bug_report, name="bug-report"),
    url(r'^contact/$', views.ajax_contact, name="contact"),


    # Profile tools
    url(r'^accounts/', include('allauth.urls'), name='accounts'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from imagekit.models import ProcessedImageField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
from decimal import Decimal
from PIL import Image
import os


ROOMMATES = (('0', '0'), ('1', '1'),
            ('2', '2'), ('3', '3'),
            ('4', '4'), ('5+', '5+'))

BED_SIZE = ((4, 'King'),
    (3, 'Queen'),
    (2, 'Full'),
    (1, 'Twin'))

BATHROOM = (('shared', 'Shared'),
    ('private', 'Private'))

YESNO = (('yes', 'Yes'), ('no', 'No'))

MAX_PHOTOS = 10
ACCEPTED_IMAGE_TYPES = ('.png', '.jpg', '.jpeg')

class Listing(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Descrition
    name = models.CharField(max_length=40, blank=True)
    summary = models.TextField(max_length=1600, blank=True)
    price = models.IntegerField(blank=True, null=True)

    # Location
    country = models.CharField(max_length=100, blank=True)  # Not used atm
    street_address = models.CharField(max_length=100, blank=True)
    apt = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=40, blank=True)
    zip_code = models.IntegerField(blank=True, null=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, default=Decimal(41.796662))
    longitude = models.DecimalField(max_digits=9, decimal_places=6, default=Decimal(-87.594183))

    # Details step
    bed_size = models.IntegerField(choices=BED_SIZE, blank=True, null=True)
    roommate_count = models.CharField(choices=ROOMMATES, max_length=5, blank=True)
    bathroom = models.CharField(choices=BATHROOM, max_length=10, blank=True)
    ac = models.BooleanField(default=False)
    in_unit_washer_dryer = models.BooleanField(default=False)
    tv = models.BooleanField(default=False)
    cable_tv = models.BooleanField(default=False)
    internet = models.BooleanField(default=False)
    wheel_chair_accessible = models.BooleanField(default=False)
    pets_live_here = models.BooleanField(default=False)

    # Calendar
    fall_quarter = models.BooleanField(default=False)
    winter_quarter = models.BooleanField(default=False)
    spring_quarter = models.BooleanField(default=False)
    summer_quarter = models.BooleanField(default=False)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)

    # Object meta data
    created_at = models.DateTimeField(auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)
    published = models.BooleanField(default=False)

    def description_complete(self):
        if self.name and self.summary and self.price:
            return True
        return False

    def location_complete(self):
        if self.street_address and self.zip_code:
            return True
        return False

    def details_complete(self):
        if self.bed_size and self.roommate_count and self.bathroom:
            return True
        return False

    def photos_complete(self):
        if Photo.objects.filter(listing=self.id):
            return True
        return False

    def calendar_complete(self):
        if self.fall_quarter or self.winter_quarter or self.spring_quarter or self.summer_quarter:
            return True
        elif self.start_date and self.end_date:
            return True
        return False

    def listing_complete(self):
        if (self.description_complete() and self.location_complete() and
            self.photos_complete() and self.details_complete() and
            self.calendar_complete()):
            return True
        self.published = False
        self.save()
        return False

    def steps_remaining(self):
        counter = 5
        if self.description_complete():
            counter -= 1
        if self.location_complete():
            counter -= 1
        if self.details_complete():
            counter -= 1
        if self.photos_complete():
            counter -= 1
        if self.calendar_complete():
            counter -= 1
        return counter

    def get_cover_photo(self):
        """TODO: This is not being used currently"""
        if self.photo_set.filter(is_cover_photo=True).count() > 0:
            return self.photo_set.filter(is_cover_photo=True)[0]
        elif self.photo_set.all().count() > 0:
            return self.photo_set.all()[0]
        else:
            return None

    def get_remaining_photos(self):
        """Currently returns all but the first photo"""
        photos = self.photo_set.filter()
        if photos.count() > 1:
            return photos[1:]
        else:
            return None

    def get_photos(self, num):
        photos = self.photo_set.filter()
        if photos.count() > 0:
            return photos[0:num]
        else:
            return None

    def get_user_url(self):
        return reverse("public_profile", kwargs={'user': self.user.id})

    def get_absolute_url(self):
        return reverse("listing", kwargs={'listing': self.id})


class Photo(models.Model):
    listing = models.ForeignKey(Listing, null=True)
    image = ProcessedImageField(
        upload_to='listing_photos/%Y/%m/%d',
        processors=[],
        format='JPEG',
        options={'quality': 90},
        null = True
    )
    image_m = ImageSpecField(
        source='image',
        processors=[ResizeToFit(width=600)],
        format='JPEG',
        options={'quality': 90}
    )
    image_s = ImageSpecField(
        source='image',
        processors=[ResizeToFit(width=400)],
        format='JPEG',
        options={'quality': 90}
    )
    description = models.CharField(max_length=100, blank=True, null=True)
    is_cover_photo = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)


    def get_delete_url(self):
        return reverse('listings:jfu_delete', kwargs={'pk': self.id})

listings/forms.py
from django import forms
from .models import Listing


class EditDescriptionForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ('name', 'summary', 'price')


class EditLocationForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ('street_address', 'apt', 'city', 'state', 'zip_code', 'latitude', 'longitude')


class EditDetailsForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ('bed_size', 'roommate_count', 'bathroom', 'ac', 'in_unit_washer_dryer', 'tv',
            'cable_tv', 'internet', 'wheel_chair_accessible', 'pets_live_here')
        widgets = {
            'bed_size': forms.Select(attrs={'class': 'ui dropdown'}),
            'bathroom': forms.Select(attrs={'class': 'ui dropdown'}),
            'roommate_count': forms.Select(attrs={'class': 'ui dropdown'}),
        }


class EditCalendarForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ('fall_quarter', 'winter_quarter', 'spring_quarter', 'summer_quarter', 'start_date', 'end_date')

listings/views.py
import os

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.http import require_POST
from django.views.generic.edit import FormView
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from .utility import listing_ownership
from .models import Listing, Photo, MAX_PHOTOS, ACCEPTED_IMAGE_TYPES
from .forms import EditDescriptionForm, EditDetailsForm, EditLocationForm, EditCalendarForm
from jfu.http import upload_receive, UploadResponse, JFUResponse

@login_required
def add_listing(request):
    new_listing = Listing(user=request.user)
    new_listing.save()
    return HttpResponseRedirect(reverse('listings:edit_listing_description', args=(new_listing.id,)))


@login_required
def edit_listing(request, listing_id):
    return HttpResponseRedirect(reverse('listings:edit_listing_description', args=(listing_id,)))


# Change these form views to one class
@login_required
@listing_ownership
def edit_listing_description(request, listing):
    if request.method == "POST":
        form = EditDescriptionForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('listings:edit_listing_location', args=(listing.id,)))
    else:
        form = EditDescriptionForm(instance=listing)
    context = {'form': form, 'user': request.user, 'listing': listing}
    return render(request, 'listing/edit_listing_description.html', context)


@login_required
@listing_ownership
def edit_listing_location(request, listing):
    if request.method == "POST":
        form = EditLocationForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('listings:edit_listing_details', args=(listing.id,)))
    else:
        form = EditLocationForm(instance=listing)
    context = {'form': form, 'user': request.user, 'listing': listing}
    return render(request, 'listing/edit_listing_location.html', context)


@login_required
@listing_ownership
def edit_listing_details(request, listing):
    if request.method == "POST":
        form = EditDetailsForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('listings:edit_listing_photos', args=(listing.id,)))
    else:
        form = EditDetailsForm(instance=listing)
    context = {'form': form, 'user': request.user, 'listing': listing}
    return render(request, 'listing/edit_listing_details.html', context)


@login_required
@listing_ownership
def edit_listing_calendar(request, listing):
    if request.method == "POST":
        form = EditCalendarForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('listings:edit_listing_calendar', args=(listing.id,)))
    else:
        form = EditCalendarForm(instance=listing)
    context = {'form': form, 'user': request.user, 'listing': listing}
    return render(request, 'listing/edit_listing_calendar.html', context)


@login_required
@listing_ownership
def edit_listing_photos(request, listing):
    photos = Photo.objects.filter(listing=listing.id)
    context = {'accepted_mime_types': 'image/*', 'listing': listing, 'photos': photos}
    return render(request, 'listing/edit_listing_photos.html', context)


@login_required
@require_POST
@listing_ownership
def upload(request, listing):
    if Photo.objects.filter(listing=listing).count() >= MAX_PHOTOS:
        return UploadResponse(request, {'error': 'Max number of photos reached.'})

    image = upload_receive(request)
    description = request.POST.get("description[]") or image.name

    if not image.name.endswith(ACCEPTED_IMAGE_TYPES):
        return UploadResponse(request, {'error': 'Filetype not supported.'})

    instance = Photo(image=image, listing=listing, description=description)
    instance.save()

    file_dict = {
        'name': image.name,
        'description': description,
        'url': instance.image.url,
        'thumbnailUrl': instance.image_s.url,
        'deleteUrl': reverse('listings:jfu_delete', kwargs={'pk': instance.pk}),
        'deleteType': 'POST',
    }
    return UploadResponse(request, file_dict)


@login_required
@require_POST
def upload_delete(request, pk):
    try:
        photo = Photo.objects.get(pk=pk)
        if photo.listing.user != request.user:
            success = False
            return JFUResponse(request, success)
        photo.delete()
        success = True
    except Photo.DoesNotExist:
        success = False
    return JFUResponse(request, success)


@login_required
@listing_ownership
def publish_listing(request, listing):
    if (listing.listing_complete()):
        listing.published = True
        listing.save()
        return HttpResponseRedirect(reverse("accounts:listings"))
    else:
        # In case someone is sneaky and tries to publish before complete
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
@listing_ownership
def unpublish_listing(request, listing):
    listing.published = False
    listing.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
@listing_ownership
def delete_listing(request, listing):
    listing.delete()
    return HttpResponseRedirect(reverse("accounts:listings"))

templates/listing/edit_listing_calendar.html
{% extends 'listing/listing_base.html' %}

{% load widget_tweaks %}
{% load staticfiles %}

{% block head_title %}Edit Calendar{% endblock %}

{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.1/css/bootstrap-datepicker3.standalone.min.css">
<style type="text/css">
  input[type=checkbox] {
    display: none;
  }
</style>
{% endblock %}

{% block listing_content %}
  <form class="ui form" method="post" action="">
      <div class="ui secondary top attached segment">
        <h3>Select the available dates</h3>
      </div>
      <div class="ui attached padded segment">
        {% csrf_token %}
        <div class="ui grid">
          <div class="row">
            <div class="four wide column">
              <div class="quarter-checkbox">
                {{ form.fall_quarter }}
                <label for="{{ form.fall_quarter.auto_id }}">
                    Fall Quarter
                </label>
              </div>
            </div>
            <div class="four wide column">
              <div class="quarter-checkbox">
                {{ form.winter_quarter }}
                <label for="{{ form.winter_quarter.auto_id }}">
                    Winter Quarter
                </label>
              </div>
            </div>
            <div class="four wide column">
              <div class="quarter-checkbox">
                {{ form.spring_quarter }}
                <label for="{{ form.spring_quarter.auto_id }}">
                    Spring Quarter
                </label>
              </div>
            </div>
            <div class="four wide column">
              <div class="quarter-checkbox">
                {{ form.summer_quarter }}
                <label for="{{ form.summer_quarter.auto_id }}">
                    Summer Quarter
                </label>
              </div>
            </div>
          </div>
          {{ form.start_date|add_class:"datepicker hidden" }}
          <div id="start_picker" data-date="01/01/2016"></div>
          {{ form.end_date|add_class:"datepicker hidden" }}
          <div id="end_picker" data-date="01/01/2016"></div>
        </div>
      </div>
      <div class="ui bottom attached segment">
        <div class="ui one column right aligned grid">
          <div class="ui sixteen wide column">
            <button class="ui customblue icon button" type="submit" style="width:90px;">Save</button>
            {% if listing.published %}
              <a href="{% url "listings:unpublish_listing" listing_id=listing.id %}" class="ui orange button">Unpublish</a>
            {% elif listing.listing_complete %}
              <a href="{% url "listings:publish_listing" listing_id=listing.id %}" class="ui green button">Publish</a>
            {% else %}
              <div class="ui disabled button">Publish</div>
            {% endif %}
          </div>
        </div>
      </div>
    </form>

{% endblock %}

{% block listing_scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.1/js/bootstrap-datepicker.min.js"></script>

<script type="text/javascript">
  $( document ).ready(function() {
      $('#start_picker').datepicker({
        format: "yyyy-mm-dd",
        startDate: "2016-01-01",
        weekStart: 1
      });
      $('#start_picker').datepicker('setDate', new Date(Date.parse("{{ listing.start_date }}")));
      $('#end_picker').datepicker({
        format: "yyyy-mm-dd",
        startDate: "2016-01-01",
        weekStart: 1
      });
      $('#end_picker').datepicker('setDate', new Date(Date.parse("{{ listing.end_date }}")));
      $('#start_picker').on("changeDate", function() {
          $('#id_start_date').val(
              $('#start_picker').datepicker('getFormattedDate')
          );
      });
      $('#start_picker').on("changeDate", function(g) {
          $('#end_picker').datepicker().datepicker('setStartDate', g.date);
      });
      $('#end_picker').on("changeDate", function() {
          $('#id_end_date').val(
              $('#end_picker').datepicker('getFormattedDate')
          );
      });
  });
</script>

{% endblock %}

templates/listing/edit_listing_description.html
{% extends 'listing/listing_base.html' %}

{% block head_title %}Edit Description{% endblock %}

{% block listing_content %}
  <form class="ui form" method="post" action="">
    <div class="ui secondary top attached segment">
      <h3>Describe your listing</h3>
    </div>
    <div class="ui attached padded segment">
      {% csrf_token %}
      <div class="ui large form">
        <div class="field">
          <label>Listing Title</label>
          {{ form.name }}
        </div>
        <div class="field">
          <label>Listing Summary</label>
          {{ form.summary }}
        </div>
        <div class="field">
          <label>Monthly rent</label>
          <div class="ui left labeled input">
            <div class="ui label">$</div>
            {{ form.price }}
          </div>
        </div>
      </div>

    </div>
    <div class="ui bottom attached segment">
      <div class="ui one column right aligned grid">
        <div class="ui sixteen wide column">
          <button class="ui customblue icon button" type="submit" style="width:90px;">Next<i class="ui right arrow icon"></i></button>
        </div>
      </div>
    </div>
  </form>

{% endblock %}

templates/listing/edit_listing_details.html
{% extends 'listing/listing_base.html' %}

{% block head_title %}Edit Details{% endblock %}

{% block listing_content %}
  <form class="ui form" method="post" action="">
      <div class="ui secondary top attached segment">
        <h3>Add some details to your listing</h3>
      </div>
      <div class="ui attached padded segment">
        {% csrf_token %}
        <div class="ui large form">
          <div class="two fields">
            <div class="field">
              <label>Bed Size</label>
              {{ form.bed_size }}
            </div>
            <div class="field">
              <label>Other Roommates</label>
              {{ form.roommate_count }}
            </div>
          </div>
          <div class="two fields">
            <div class="field">
              <label>Bathroom</label>
              {{ form.bathroom }}
            </div>
          </div>

          <div class="ui divider"></div>

          <div class="two fields">
            <div class="inline field">
              <div class="ui checkbox">
                <label><strong>Air Conditioning</strong></label>
                {{ form.ac }}
              </div>
            </div>
            <div class="inline field">
              <div class="ui checkbox">
                <label><strong>Internet</strong></label>
                {{ form.internet }}
              </div>
            </div>
          </div>

          <div class="two fields">
            <div class="inline field">
              <div class="ui checkbox">
                <label><strong>In-unit washer and dryer</strong></label>
                {{ form.in_unit_washer_dryer }}
              </div>
            </div>
            <div class="inline field">
              <div class="ui checkbox">
                <label><strong>Wheelchair accessible</strong></label>
                {{ form.wheel_chair_accessible }}
              </div>
            </div>
          </div>

          <div class="two fields">
            <div class="inline field">
              <div class="ui checkbox">
                <label><strong>TV</strong></label>
                {{ form.tv }}
              </div>
            </div>
            <div class="inline field">
              <div class="ui checkbox">
                <label><strong>Pets live here</strong></label>
                {{ form.pets_live_here }}
              </div>
            </div>
          </div>

          <div class="two fields">
            <div class="inline field">
              <div class="ui checkbox">
                <label><strong>Cable TV</strong></label>
                {{ form.cable_tv }}
              </div>
            </div>
          </div>

        </div>
      </div>
      <div class="ui bottom attached segment">
        <div class="ui one column right aligned grid">
          <div class="ui sixteen wide column">
            <button class="ui customblue icon button" type="submit" style="width:90px;">Next<i class="ui right arrow icon"></i></button>
          </div>
        </div>
      </div>
    </form>

{% endblock %}

templates/listing/listing_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title %}{% block listing_head_title %}{% endblock %}{% endblock %}
{% block content %}

<div id="account" class="ui centered two column grid stackable container" style="margin-top: 20px;">
  <div class="four wide column">
    <div class="ui large one item menu">
      <a href="{% url 'accounts:listings' %}" class="ui item">
        <i class="ui arrow left icon"></i>
        Back to Dashboard
      </a>
    </div>

    <div class="ui large vertical fluid menu">
      <div class="header center aligned item">
        <div class="ui center aligned small header">
          Listing Steps
        </div>
      </div>
      <a href="{% url 'listings:edit_listing_description' listing_id=listing.id %}"  class=" {% if request.resolver_match.url_name == "edit_listing_description" %}active{% endif %} item">
        Description
        {% if listing.description_complete %}
        <i class="ui green checkmark icon"></i>
        {% else %}
        <i class="ui grey plus icon"></i>
        {% endif %}
      </a>
      <a href="{% url 'listings:edit_listing_location' listing_id=listing.id %}" class="{% if request.resolver_match.url_name == "edit_listing_location" %}active{% endif %} item">
        Location
        {% if listing.location_complete %}
        <i class="ui green checkmark icon"></i>
        {% else %}
        <i class="ui grey plus icon"></i>
        {% endif %}
      </a>
      <a href="{% url 'listings:edit_listing_details' listing_id=listing.id %}" class="{% if request.resolver_match.url_name == "edit_listing_details" %}active{% endif %} item">
        Details
        {% if listing.details_complete %}
        <i class="ui green checkmark icon"></i>
        {% else %}
        <i class="ui grey plus icon"></i>
        {% endif %}
      </a>
      <a href="{% url 'listings:edit_listing_photos' listing_id=listing.id %}" class="{% if request.resolver_match.url_name == "edit_listing_photos" %}active{% endif %} item">
        Photos
        {% if listing.photos_complete %}
        <i class="ui green checkmark icon"></i>
        {% else %}
        <i class="ui grey plus icon"></i>
        {% endif %}
      </a>
      <a href="{% url 'listings:edit_listing_calendar' listing_id=listing.id %}" class="{% if request.resolver_match.url_name == "edit_listing_calendar" %}active{% endif %} item">
        Calendar
        {% if listing.calendar_complete %}
        <i class="ui green checkmark icon"></i>
        {% else %}
        <i class="ui grey plus icon"></i>
        {% endif %}
      </a>
    </div>

    <div class="ui card">
      <div class="content">
        {% if listing.listing_complete %}
        <div class="ui center aligned header">
          Ready to publish!
        </div>
        <div class="description">
          You are ready to publish your listing. Don't worry you can come back and edit it later.
        </div>
        {% elif listing.published %}
        <div class="ui center aligned header">
          Currently published
        </div>
        <div class="description">
          This listing is currently published and publicly accessible. You can temporarily unpublish the listing.
        </div>
        {% else %}
        <div class="ui center aligned header">
          Steps remaining: {{ listing.steps_remaining }}
        </div>
        <div class="description">
          To publish your listing complete the steps above. You can always come back and finish it later.
        </div>
        {% endif %}
      </div>
      <div class="extra content">
        {% if listing.published %}
        <a href="{% url "listings:unpublish_listing" listing_id=listing.id %}" class="ui orange button">Unpublish</a>
        {% elif listing.listing_complete %}
        <a href="{% url "listings:publish_listing" listing_id=listing.id %}" class="ui green button">Publish</a>
        {% else %}
        <div class="ui disabled button">Publish</div>
        {% endif %}
        <a href="{% url "listings:delete_listing" listing_id=listing.id %}" id="delete-listing" class="ui red delete button">Delete</a>
      </div>
    </div>
  </div>

  <div class="nine wide column">
    {% block listing_content %}
    {% endblock %}
  </div>
</div>

<div id="confirm_delete" class="ui small modal">
  <div class="header">
    Delete listing
  </div>
  <div class="content">
    <p>Are you sure you want to delete this listing? You will not be able to retrieve it if deleted.</p>
  </div>
  <div class="actions">
    <div class="ui cancel button">
      Cancel
    </div>
    <div class="ui negative approve right labeled icon button">
      Yes
      <i class="remove icon"></i>
    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
  {% block listing_scripts %}
  {% endblock %}

  <script type="text/javascript">
    $('#delete-listing').click(function(){
      event.preventDefault();
      var deleteLink = $(this).attr("href");
      var row = $(this).parents('.ui.row');
      var divider = row.prev('.divider');
      $('#confirm_delete').modal({
        onApprove : function() {
          $.get(deleteLink);
          divider.hide("medium", function() {
            $(this).remove();
          });
          row.hide("medium", function() {
            $(this).remove();
          });
        }
      })
      .modal('show');
    });
  </script>
{% endblock %}